# -*- coding: utf-8 -*-
"""ChatBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CvDVnw9U0w-mgUzo-zHt9CHchXBfR-1B
"""

from google.generativeai import GenerativeModel,configure

# Replace with your Gemini API key
configure(api_key="API_KEY")
model = GenerativeModel("gemini-1.5-pro")

def chat():
  print("Chatbot: Hi! How can I help you today?")
  messages = [{"role": "system", "content": "You are a helpful assistant."}]
  while True:
    user_input = input("You: ")
    if user_input.lower() in ["exit", "quit", "bye"]:
      print("Chatbot: Goodbye!")
      break
    elif user_input.lower():
      r=model.generate_content(user_input)
      print("Chatbot:",r.text)
    else:
      print("Chatbot: Sorry, I didn't understand that.")

if __name__ == "__main__":
    chat()

